### ISSUE TITLE
We are creating an awesome feature

### ISSUE THREAD

**Issue by sunxiaoguang** [sunxiaoguang/pingcap-newbie-workshop#4]
Here is the design doc:

https://docs.google.com/document/d/1J1nwAs8aC8gjFqoPMWSGI9Iemh23mslah_XUMxHtTbs/edit

**Comment by lilin90** [comment]
I have no access to this doc.

**Comment by sunxiaoguang** [comment]
Sorry for making such mistake. Let's update a new design doc with public access.
